/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface AdminDashboard {
  totalUsers: number;
  activeUsers: number;
  totalSignals: number;
  botUptime: string;
  winRate: number;
  lossRate: number;
  telegramSubscribers: number;
  todaySignals: number;
  autoAnalysisEnabled: boolean;
  totalProfit?: number;
}
