/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface AdminLog {
  id: number;
  action: string;
  /** @nullable */
  userId: number | null;
  details: string;
  createdAt: string;
}
