/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface RegisterInput {
  email: string;
  password: string;
  username: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export interface User {
  id: number;
  email: string;
  username: string;
  role: UserRole;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export interface ForexPair {
  id: number;
  symbol: string;
  name: string;
  category: string;
  enabled: boolean;
  /** @nullable */
  currentPrice?: number | null;
  /** @nullable */
  priceChange?: number | null;
  /** @nullable */
  spread?: number | null;
  /** @nullable */
  volatility?: string | null;
  /** @nullable */
  trend?: string | null;
  /** @nullable */
  bias?: string | null;
  /** @nullable */
  confidence?: number | null;
  /** @nullable */
  updatedAt?: string | null;
}

export interface LivePrice {
  symbol: string;
  price: number;
  change: number;
  changePercent: number;
  high?: number;
  low?: number;
  /** @nullable */
  volume?: number | null;
  timestamp: string;
}

export type SignalDirection = typeof SignalDirection[keyof typeof SignalDirection];


export const SignalDirection = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;

export interface Signal {
  id: number;
  pair: string;
  direction: SignalDirection;
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  confidence: number;
  /** @nullable */
  trend?: string | null;
  /** @nullable */
  explanation?: string | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  pips?: number | null;
  telegramSent?: boolean;
  createdAt: string;
  /** @nullable */
  closedAt?: string | null;
  /** @nullable */
  rsi?: number | null;
  /** @nullable */
  macd?: number | null;
  /** @nullable */
  ema50?: number | null;
  /** @nullable */
  ema200?: number | null;
  /** @nullable */
  atr?: number | null;
  /** @nullable */
  session?: string | null;
}

export interface SignalGenerateInput {
  symbol: string;
  sendTelegram?: boolean;
}

export type SignalResultInputResult = typeof SignalResultInputResult[keyof typeof SignalResultInputResult];


export const SignalResultInputResult = {
  win: 'win',
  loss: 'loss',
  breakeven: 'breakeven',
} as const;

export interface SignalResultInput {
  result: SignalResultInputResult;
  /** @nullable */
  pips?: number | null;
}

export interface SignalList {
  signals: Signal[];
  total: number;
}

export interface MarketAnalysis {
  symbol: string;
  direction: string;
  confidence: number;
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  rsi: number;
  macd: number;
  ema50: number;
  ema200: number;
  atr: number;
  trend: string;
  explanation: string;
  session: string;
  breakout?: boolean;
  bosDetected?: boolean;
  chochDetected?: boolean;
  fvgDetected?: boolean;
  liquiditySweep?: boolean;
  generatedAt: string;
}

export interface DetectorCard {
  name: string;
  status: string;
  accuracy: number;
  confidence: number;
  detail: string;
}

export interface DetectorReadings {
  symbol: string;
  trend: DetectorCard;
  liquidity: DetectorCard;
  breakout: DetectorCard;
  volatility: DetectorCard;
  momentum: DetectorCard;
  session: DetectorCard;
  newsImpact: DetectorCard;
}

export interface StatsOverview {
  totalSignals: number;
  totalWins: number;
  totalLosses: number;
  totalBreakeven: number;
  winRate: number;
  totalPips: number;
  /** @nullable */
  bestPair: string | null;
  /** @nullable */
  worstPair: string | null;
  dailyProfit: number;
  weeklyProfit: number;
  monthlyProfit: number;
  todaySignals: number;
  activeSubscribers: number;
}

export interface PerformancePoint {
  date: string;
  profit: number;
  winRate: number;
  signals: number;
}

export interface PairStat {
  symbol: string;
  totalSignals: number;
  wins: number;
  losses: number;
  winRate: number;
  totalPips: number;
}

export interface AdminDashboard {
  totalUsers: number;
  activeUsers: number;
  totalSignals: number;
  botUptime: string;
  winRate: number;
  lossRate: number;
  telegramSubscribers: number;
  todaySignals: number;
  autoAnalysisEnabled: boolean;
  totalProfit?: number;
}

export interface AdminLog {
  id: number;
  action: string;
  /** @nullable */
  userId: number | null;
  details: string;
  createdAt: string;
}

export interface TogglePairInput {
  enabled: boolean;
}

export interface ToggleAutoAnalysisInput {
  enabled: boolean;
}

export interface AdminSendSignalInput {
  signalId: number;
}

export interface BotSettings {
  id: number;
  autoAnalysisEnabled: boolean;
  analysisIntervalMinutes: number;
  telegramEnabled: boolean;
  hasTelegramToken?: boolean;
  hasTwelveDataKey?: boolean;
  hasAlphaVantageKey?: boolean;
  hasOpenAiKey?: boolean;
  hasBinanceKey?: boolean;
  updatedAt: string;
}

export interface BotSettingsInput {
  telegramBotToken?: string;
  twelveDataApiKey?: string;
  alphaVantageApiKey?: string;
  openAiApiKey?: string;
  binanceApiKey?: string;
  autoAnalysisEnabled?: boolean;
  analysisIntervalMinutes?: number;
  telegramEnabled?: boolean;
}

export type TelegramSubscriberTier = typeof TelegramSubscriberTier[keyof typeof TelegramSubscriberTier];


export const TelegramSubscriberTier = {
  free: 'free',
  premium: 'premium',
} as const;

export interface TelegramSubscriber {
  id: number;
  chatId: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  firstName?: string | null;
  tier: TelegramSubscriberTier;
  active: boolean;
  subscribedAt: string;
}

export type BroadcastInputTier = typeof BroadcastInputTier[keyof typeof BroadcastInputTier];


export const BroadcastInputTier = {
  all: 'all',
  free: 'free',
  premium: 'premium',
} as const;

export interface BroadcastInput {
  message: string;
  tier?: BroadcastInputTier;
}

export interface TelegramBroadcastResult {
  sent: number;
  failed: number;
  total: number;
}

export interface WebhookUpdate {
  update_id?: number;
}

export interface WebhookAck {
  ok: boolean;
}

export type ListSignalsParams = {
pair?: string;
result?: string;
limit?: number;
offset?: number;
};

export type GetPerformanceParams = {
period?: GetPerformancePeriod;
};

export type GetPerformancePeriod = typeof GetPerformancePeriod[keyof typeof GetPerformancePeriod];


export const GetPerformancePeriod = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;

