/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Register a new user
 */
export const RegisterBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "username": zod.string()
})


/**
 * @summary Login
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'user']),
  "createdAt": zod.string()
})
})


/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'user']),
  "createdAt": zod.string()
})


/**
 * @summary List all forex pairs
 */
export const ListPairsResponseItem = zod.object({
  "id": zod.number(),
  "symbol": zod.string(),
  "name": zod.string(),
  "category": zod.string(),
  "enabled": zod.boolean(),
  "currentPrice": zod.number().nullish(),
  "priceChange": zod.number().nullish(),
  "spread": zod.number().nullish(),
  "volatility": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "bias": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "updatedAt": zod.string().nullish()
})
export const ListPairsResponse = zod.array(ListPairsResponseItem)


/**
 * @summary Get a forex pair by symbol
 */
export const GetPairParams = zod.object({
  "symbol": zod.coerce.string()
})

export const GetPairResponse = zod.object({
  "id": zod.number(),
  "symbol": zod.string(),
  "name": zod.string(),
  "category": zod.string(),
  "enabled": zod.boolean(),
  "currentPrice": zod.number().nullish(),
  "priceChange": zod.number().nullish(),
  "spread": zod.number().nullish(),
  "volatility": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "bias": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "updatedAt": zod.string().nullish()
})


/**
 * @summary Get live price for a pair
 */
export const GetPairPriceParams = zod.object({
  "symbol": zod.coerce.string()
})

export const GetPairPriceResponse = zod.object({
  "symbol": zod.string(),
  "price": zod.number(),
  "change": zod.number(),
  "changePercent": zod.number(),
  "high": zod.number().optional(),
  "low": zod.number().optional(),
  "volume": zod.number().nullish(),
  "timestamp": zod.string()
})


/**
 * @summary List signals with optional filters
 */
export const ListSignalsQueryParams = zod.object({
  "pair": zod.coerce.string().optional(),
  "result": zod.coerce.string().optional(),
  "limit": zod.coerce.number().optional(),
  "offset": zod.coerce.number().optional()
})

export const ListSignalsResponse = zod.object({
  "signals": zod.array(zod.object({
  "id": zod.number(),
  "pair": zod.string(),
  "direction": zod.enum(['BUY', 'SELL']),
  "entryPrice": zod.number(),
  "stopLoss": zod.number(),
  "takeProfit1": zod.number(),
  "takeProfit2": zod.number(),
  "confidence": zod.number(),
  "trend": zod.string().nullish(),
  "explanation": zod.string().nullish(),
  "result": zod.string().nullish(),
  "pips": zod.number().nullish(),
  "telegramSent": zod.boolean().optional(),
  "createdAt": zod.string(),
  "closedAt": zod.string().nullish(),
  "rsi": zod.number().nullish(),
  "macd": zod.number().nullish(),
  "ema50": zod.number().nullish(),
  "ema200": zod.number().nullish(),
  "atr": zod.number().nullish(),
  "session": zod.string().nullish()
})),
  "total": zod.number()
})


/**
 * @summary Generate a new signal for a pair
 */
export const GenerateSignalBody = zod.object({
  "symbol": zod.string(),
  "sendTelegram": zod.boolean().optional()
})


/**
 * @summary Get a signal by ID
 */
export const GetSignalParams = zod.object({
  "id": zod.coerce.number()
})

export const GetSignalResponse = zod.object({
  "id": zod.number(),
  "pair": zod.string(),
  "direction": zod.enum(['BUY', 'SELL']),
  "entryPrice": zod.number(),
  "stopLoss": zod.number(),
  "takeProfit1": zod.number(),
  "takeProfit2": zod.number(),
  "confidence": zod.number(),
  "trend": zod.string().nullish(),
  "explanation": zod.string().nullish(),
  "result": zod.string().nullish(),
  "pips": zod.number().nullish(),
  "telegramSent": zod.boolean().optional(),
  "createdAt": zod.string(),
  "closedAt": zod.string().nullish(),
  "rsi": zod.number().nullish(),
  "macd": zod.number().nullish(),
  "ema50": zod.number().nullish(),
  "ema200": zod.number().nullish(),
  "atr": zod.number().nullish(),
  "session": zod.string().nullish()
})


/**
 * @summary Update signal win/loss result
 */
export const UpdateSignalResultParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateSignalResultBody = zod.object({
  "result": zod.enum(['win', 'loss', 'breakeven']),
  "pips": zod.number().nullish()
})

export const UpdateSignalResultResponse = zod.object({
  "id": zod.number(),
  "pair": zod.string(),
  "direction": zod.enum(['BUY', 'SELL']),
  "entryPrice": zod.number(),
  "stopLoss": zod.number(),
  "takeProfit1": zod.number(),
  "takeProfit2": zod.number(),
  "confidence": zod.number(),
  "trend": zod.string().nullish(),
  "explanation": zod.string().nullish(),
  "result": zod.string().nullish(),
  "pips": zod.number().nullish(),
  "telegramSent": zod.boolean().optional(),
  "createdAt": zod.string(),
  "closedAt": zod.string().nullish(),
  "rsi": zod.number().nullish(),
  "macd": zod.number().nullish(),
  "ema50": zod.number().nullish(),
  "ema200": zod.number().nullish(),
  "atr": zod.number().nullish(),
  "session": zod.string().nullish()
})


/**
 * @summary Run live market analysis for a pair
 */
export const GetAnalysisParams = zod.object({
  "symbol": zod.coerce.string()
})

export const GetAnalysisResponse = zod.object({
  "symbol": zod.string(),
  "direction": zod.string(),
  "confidence": zod.number(),
  "entryPrice": zod.number(),
  "stopLoss": zod.number(),
  "takeProfit1": zod.number(),
  "takeProfit2": zod.number(),
  "rsi": zod.number(),
  "macd": zod.number(),
  "ema50": zod.number(),
  "ema200": zod.number(),
  "atr": zod.number(),
  "trend": zod.string(),
  "explanation": zod.string(),
  "session": zod.string(),
  "breakout": zod.boolean().optional(),
  "bosDetected": zod.boolean().optional(),
  "chochDetected": zod.boolean().optional(),
  "fvgDetected": zod.boolean().optional(),
  "liquiditySweep": zod.boolean().optional(),
  "generatedAt": zod.string()
})


/**
 * @summary Get detector readings for a pair
 */
export const GetDetectorsParams = zod.object({
  "symbol": zod.coerce.string()
})

export const GetDetectorsResponse = zod.object({
  "symbol": zod.string(),
  "trend": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "liquidity": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "breakout": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "volatility": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "momentum": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "session": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
}),
  "newsImpact": zod.object({
  "name": zod.string(),
  "status": zod.string(),
  "accuracy": zod.number(),
  "confidence": zod.number(),
  "detail": zod.string()
})
})


/**
 * @summary Get overall trading statistics
 */
export const GetStatsOverviewResponse = zod.object({
  "totalSignals": zod.number(),
  "totalWins": zod.number(),
  "totalLosses": zod.number(),
  "totalBreakeven": zod.number(),
  "winRate": zod.number(),
  "totalPips": zod.number(),
  "bestPair": zod.string().nullable(),
  "worstPair": zod.string().nullable(),
  "dailyProfit": zod.number(),
  "weeklyProfit": zod.number(),
  "monthlyProfit": zod.number(),
  "todaySignals": zod.number(),
  "activeSubscribers": zod.number()
})


/**
 * @summary Get profit/win-rate time series
 */
export const GetPerformanceQueryParams = zod.object({
  "period": zod.enum(['daily', 'weekly', 'monthly']).optional()
})

export const GetPerformanceResponseItem = zod.object({
  "date": zod.string(),
  "profit": zod.number(),
  "winRate": zod.number(),
  "signals": zod.number()
})
export const GetPerformanceResponse = zod.array(GetPerformanceResponseItem)


/**
 * @summary Get win/loss stats per pair
 */
export const GetPairStatsResponseItem = zod.object({
  "symbol": zod.string(),
  "totalSignals": zod.number(),
  "wins": zod.number(),
  "losses": zod.number(),
  "winRate": zod.number(),
  "totalPips": zod.number()
})
export const GetPairStatsResponse = zod.array(GetPairStatsResponseItem)


/**
 * @summary Get admin dashboard summary
 */
export const GetAdminDashboardResponse = zod.object({
  "totalUsers": zod.number(),
  "activeUsers": zod.number(),
  "totalSignals": zod.number(),
  "botUptime": zod.string(),
  "winRate": zod.number(),
  "lossRate": zod.number(),
  "telegramSubscribers": zod.number(),
  "todaySignals": zod.number(),
  "autoAnalysisEnabled": zod.boolean(),
  "totalProfit": zod.number().optional()
})


/**
 * @summary List all users
 */
export const ListUsersResponseItem = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "username": zod.string(),
  "role": zod.enum(['admin', 'user']),
  "createdAt": zod.string()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary List admin activity logs
 */
export const ListAdminLogsResponseItem = zod.object({
  "id": zod.number(),
  "action": zod.string(),
  "userId": zod.number().nullable(),
  "details": zod.string(),
  "createdAt": zod.string()
})
export const ListAdminLogsResponse = zod.array(ListAdminLogsResponseItem)


/**
 * @summary Enable or disable a forex pair
 */
export const TogglePairParams = zod.object({
  "symbol": zod.coerce.string()
})

export const TogglePairBody = zod.object({
  "enabled": zod.boolean()
})

export const TogglePairResponse = zod.object({
  "id": zod.number(),
  "symbol": zod.string(),
  "name": zod.string(),
  "category": zod.string(),
  "enabled": zod.boolean(),
  "currentPrice": zod.number().nullish(),
  "priceChange": zod.number().nullish(),
  "spread": zod.number().nullish(),
  "volatility": zod.string().nullish(),
  "trend": zod.string().nullish(),
  "bias": zod.string().nullish(),
  "confidence": zod.number().nullish(),
  "updatedAt": zod.string().nullish()
})


/**
 * @summary Enable or disable automatic analysis cron
 */
export const ToggleAutoAnalysisBody = zod.object({
  "enabled": zod.boolean()
})

export const ToggleAutoAnalysisResponse = zod.object({
  "id": zod.number(),
  "autoAnalysisEnabled": zod.boolean(),
  "analysisIntervalMinutes": zod.number(),
  "telegramEnabled": zod.boolean(),
  "hasTelegramToken": zod.boolean().optional(),
  "hasTwelveDataKey": zod.boolean().optional(),
  "hasAlphaVantageKey": zod.boolean().optional(),
  "hasOpenAiKey": zod.boolean().optional(),
  "hasBinanceKey": zod.boolean().optional(),
  "updatedAt": zod.string()
})


/**
 * @summary Admin manually sends a signal to Telegram
 */
export const AdminSendSignalBody = zod.object({
  "signalId": zod.number()
})

export const AdminSendSignalResponse = zod.object({
  "sent": zod.number(),
  "failed": zod.number(),
  "total": zod.number()
})


/**
 * @summary Get bot settings (admin only)
 */
export const GetSettingsResponse = zod.object({
  "id": zod.number(),
  "autoAnalysisEnabled": zod.boolean(),
  "analysisIntervalMinutes": zod.number(),
  "telegramEnabled": zod.boolean(),
  "hasTelegramToken": zod.boolean().optional(),
  "hasTwelveDataKey": zod.boolean().optional(),
  "hasAlphaVantageKey": zod.boolean().optional(),
  "hasOpenAiKey": zod.boolean().optional(),
  "hasBinanceKey": zod.boolean().optional(),
  "updatedAt": zod.string()
})


/**
 * @summary Update bot settings (admin only)
 */
export const UpdateSettingsBody = zod.object({
  "telegramBotToken": zod.string().optional(),
  "twelveDataApiKey": zod.string().optional(),
  "alphaVantageApiKey": zod.string().optional(),
  "openAiApiKey": zod.string().optional(),
  "binanceApiKey": zod.string().optional(),
  "autoAnalysisEnabled": zod.boolean().optional(),
  "analysisIntervalMinutes": zod.number().optional(),
  "telegramEnabled": zod.boolean().optional()
})

export const UpdateSettingsResponse = zod.object({
  "id": zod.number(),
  "autoAnalysisEnabled": zod.boolean(),
  "analysisIntervalMinutes": zod.number(),
  "telegramEnabled": zod.boolean(),
  "hasTelegramToken": zod.boolean().optional(),
  "hasTwelveDataKey": zod.boolean().optional(),
  "hasAlphaVantageKey": zod.boolean().optional(),
  "hasOpenAiKey": zod.boolean().optional(),
  "hasBinanceKey": zod.boolean().optional(),
  "updatedAt": zod.string()
})


/**
 * @summary List Telegram subscribers
 */
export const ListSubscribersResponseItem = zod.object({
  "id": zod.number(),
  "chatId": zod.string(),
  "username": zod.string().nullable(),
  "firstName": zod.string().nullish(),
  "tier": zod.enum(['free', 'premium']),
  "active": zod.boolean(),
  "subscribedAt": zod.string()
})
export const ListSubscribersResponse = zod.array(ListSubscribersResponseItem)


/**
 * @summary Broadcast a message to all subscribers
 */
export const BroadcastMessageBody = zod.object({
  "message": zod.string(),
  "tier": zod.enum(['all', 'free', 'premium']).optional()
})

export const BroadcastMessageResponse = zod.object({
  "sent": zod.number(),
  "failed": zod.number(),
  "total": zod.number()
})


/**
 * @summary Telegram webhook receiver
 */
export const TelegramWebhookBody = zod.object({
  "update_id": zod.number().optional()
})

export const TelegramWebhookResponse = zod.object({
  "ok": zod.boolean()
})


