/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface BotSettingsInput {
  telegramBotToken?: string;
  twelveDataApiKey?: string;
  alphaVantageApiKey?: string;
  openAiApiKey?: string;
  binanceApiKey?: string;
  autoAnalysisEnabled?: boolean;
  analysisIntervalMinutes?: number;
  telegramEnabled?: boolean;
}
