/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface BotSettings {
  id: number;
  autoAnalysisEnabled: boolean;
  analysisIntervalMinutes: number;
  telegramEnabled: boolean;
  hasTelegramToken?: boolean;
  hasTwelveDataKey?: boolean;
  hasAlphaVantageKey?: boolean;
  hasOpenAiKey?: boolean;
  hasBinanceKey?: boolean;
  updatedAt: string;
}
