/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export type BroadcastInputTier = typeof BroadcastInputTier[keyof typeof BroadcastInputTier];


export const BroadcastInputTier = {
  all: 'all',
  free: 'free',
  premium: 'premium',
} as const;
