/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { BroadcastInputTier } from './broadcastInputTier';

export interface BroadcastInput {
  message: string;
  tier?: BroadcastInputTier;
}
