/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { DetectorCard } from './detectorCard';

export interface DetectorReadings {
  symbol: string;
  trend: DetectorCard;
  liquidity: DetectorCard;
  breakout: DetectorCard;
  volatility: DetectorCard;
  momentum: DetectorCard;
  session: DetectorCard;
  newsImpact: DetectorCard;
}
