/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface ForexPair {
  id: number;
  symbol: string;
  name: string;
  category: string;
  enabled: boolean;
  /** @nullable */
  currentPrice?: number | null;
  /** @nullable */
  priceChange?: number | null;
  /** @nullable */
  spread?: number | null;
  /** @nullable */
  volatility?: string | null;
  /** @nullable */
  trend?: string | null;
  /** @nullable */
  bias?: string | null;
  /** @nullable */
  confidence?: number | null;
  /** @nullable */
  updatedAt?: string | null;
}
