/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export type GetPerformancePeriod = typeof GetPerformancePeriod[keyof typeof GetPerformancePeriod];


export const GetPerformancePeriod = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
