/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface MarketAnalysis {
  symbol: string;
  direction: string;
  confidence: number;
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  rsi: number;
  macd: number;
  ema50: number;
  ema200: number;
  atr: number;
  trend: string;
  explanation: string;
  session: string;
  breakout?: boolean;
  bosDetected?: boolean;
  chochDetected?: boolean;
  fvgDetected?: boolean;
  liquiditySweep?: boolean;
  generatedAt: string;
}
