/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface PairStat {
  symbol: string;
  totalSignals: number;
  wins: number;
  losses: number;
  winRate: number;
  totalPips: number;
}
