/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export type SignalResultInputResult = typeof SignalResultInputResult[keyof typeof SignalResultInputResult];


export const SignalResultInputResult = {
  win: 'win',
  loss: 'loss',
  breakeven: 'breakeven',
} as const;
