/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { SignalDirection } from './signalDirection';

export interface Signal {
  id: number;
  pair: string;
  direction: SignalDirection;
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  confidence: number;
  /** @nullable */
  trend?: string | null;
  /** @nullable */
  explanation?: string | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  pips?: number | null;
  telegramSent?: boolean;
  createdAt: string;
  /** @nullable */
  closedAt?: string | null;
  /** @nullable */
  rsi?: number | null;
  /** @nullable */
  macd?: number | null;
  /** @nullable */
  ema50?: number | null;
  /** @nullable */
  ema200?: number | null;
  /** @nullable */
  atr?: number | null;
  /** @nullable */
  session?: string | null;
}
