/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { Signal } from './signal';

export interface SignalList {
  signals: Signal[];
  total: number;
}
