/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface StatsOverview {
  totalSignals: number;
  totalWins: number;
  totalLosses: number;
  totalBreakeven: number;
  winRate: number;
  totalPips: number;
  /** @nullable */
  bestPair: string | null;
  /** @nullable */
  worstPair: string | null;
  dailyProfit: number;
  weeklyProfit: number;
  monthlyProfit: number;
  todaySignals: number;
  activeSubscribers: number;
}
