/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */

export type TelegramSubscriberTier = typeof TelegramSubscriberTier[keyof typeof TelegramSubscriberTier];


export const TelegramSubscriberTier = {
  free: 'free',
  premium: 'premium',
} as const;
