/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ForexSignal AI Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { TelegramSubscriberTier } from './telegramSubscriberTier';

export interface TelegramSubscriber {
  id: number;
  chatId: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  firstName?: string | null;
  tier: TelegramSubscriberTier;
  active: boolean;
  subscribedAt: string;
}
